# Generated by Django 5.2.17 on 2026-09-15 16:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("osm_way_id", models.BigIntegerField()),
                ("ordinal", models.IntegerField()),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.LineStringField(srid=4326),
                ),
                (
                    "stress_tier",
                    models.IntegerField(
                        choices=[
                            (1, "Tolerable for most adults and children"),
                            (2, "Tolerable for most adults"),
                            (3, "Tolerable for confident cyclists"),
                            (4, "Strong and fearless only"),
                        ]
                    ),
                ),
                ("stress_rule", models.TextField()),
                ("stress_assumed", models.JSONField(default=list)),
                ("volume_source", models.TextField(blank=True, null=True)),
                ("sinuosity", models.FloatField(null=True)),
                ("is_trail_class", models.BooleanField(default=False)),
                ("is_unpaved", models.BooleanField(default=False)),
                ("is_rough", models.BooleanField(default=False)),
                ("lit", models.BooleanField(null=True)),
            ],
            options={
                "db_table": "segment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BorderCrossing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_id", models.BigIntegerField(unique=True)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("osm_way_id", models.BigIntegerField()),
                ("state_a", models.CharField(max_length=2)),
                ("state_b", models.CharField(max_length=2)),
            ],
            options={
                "db_table": "border_crossing",
                "indexes": [
                    models.Index(
                        fields=["osm_way_id"], name="border_cros_osm_way_efb172_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Jurisdiction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "layer",
                    models.CharField(
                        choices=[
                            ("police", "Police authority"),
                            ("row", "Right-of-way owner"),
                            ("manager", "Park or trail manager"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.TextField()),
                ("state", models.CharField(blank=True, max_length=2, null=True)),
                ("is_federal_enclave", models.BooleanField(default=False)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
            options={
                "db_table": "jurisdiction",
                "indexes": [
                    models.Index(fields=["layer"], name="jurisdictio_layer_710412_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Override",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("access", "Bicycle access"),
                            ("stress", "Stress tier"),
                            ("jurisdiction", "Authority assignment"),
                        ],
                        max_length=16,
                    ),
                ),
                ("osm_way_id", models.BigIntegerField()),
                ("value", models.JSONField()),
                ("reason", models.TextField()),
                (
                    "evidence",
                    models.TextField(
                        help_text="Why this row is correct. A check-only source may never be the sole basis for an override: a discrepancy it surfaces is resolved by independent re-derivation from OSM, federal, or CC0 inputs."
                    ),
                ),
                ("approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "override",
                "indexes": [
                    models.Index(
                        fields=["osm_way_id", "approved"],
                        name="override_osm_way_aa50c8_idx",
                    )
                ],
            },
        ),
    ]
