# Generated by Django 5.2.17 on 2026-09-15 19:41

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("osm_way_id", models.BigIntegerField()),
                ("ordinal", models.IntegerField()),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.LineStringField(srid=4326),
                ),
                (
                    "stress_tier",
                    models.IntegerField(
                        choices=[
                            (1, "Tolerable for most adults and children"),
                            (2, "Tolerable for most adults"),
                            (3, "Tolerable for confident cyclists"),
                            (4, "Strong and fearless only"),
                        ]
                    ),
                ),
                ("stress_rule", models.TextField()),
                ("stress_assumed", models.JSONField(default=list)),
                ("volume_source", models.TextField(blank=True, null=True)),
                ("sinuosity", models.FloatField(null=True)),
                ("is_trail_class", models.BooleanField(default=False)),
                ("is_unpaved", models.BooleanField(null=True)),
                ("is_rough", models.BooleanField(default=False)),
                ("lit", models.BooleanField(null=True)),
            ],
            options={
                "db_table": "segment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("discord_user_id", models.BigIntegerField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("session_epoch", models.IntegerField(default=1)),
                ("is_banned", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_instance_admin", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "app_user",
            },
        ),
        migrations.CreateModel(
            name="BanTombstone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tombstone", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True)),
            ],
            options={
                "db_table": "ban_tombstone",
            },
        ),
        migrations.CreateModel(
            name="ConfiguredGuild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guild_id", models.BigIntegerField(unique=True)),
                ("name", models.TextField(blank=True)),
                ("admin_contact_email", models.EmailField(blank=True, max_length=254)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("degraded", "Degraded"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("state_since", models.DateTimeField(auto_now_add=True)),
                ("standing_valid_until", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "configured_guild",
            },
        ),
        migrations.CreateModel(
            name="BorderCrossing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_id", models.BigIntegerField(unique=True)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("osm_way_id", models.BigIntegerField()),
                ("state_a", models.CharField(max_length=2)),
                ("state_b", models.CharField(max_length=2)),
            ],
            options={
                "db_table": "border_crossing",
                "indexes": [
                    models.Index(
                        fields=["osm_way_id"], name="border_cros_osm_way_efb172_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Jurisdiction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "layer",
                    models.CharField(
                        choices=[
                            ("police", "Police authority"),
                            ("row", "Right-of-way owner"),
                            ("manager", "Park or trail manager"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.TextField()),
                ("state", models.CharField(blank=True, max_length=2, null=True)),
                ("is_federal_enclave", models.BooleanField(default=False)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
            options={
                "db_table": "jurisdiction",
                "indexes": [
                    models.Index(fields=["layer"], name="jurisdictio_layer_710412_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Override",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("access", "Bicycle access"),
                            ("stress", "Stress tier"),
                            ("jurisdiction", "Authority assignment"),
                        ],
                        max_length=16,
                    ),
                ),
                ("osm_way_id", models.BigIntegerField()),
                ("value", models.JSONField()),
                ("reason", models.TextField()),
                (
                    "evidence",
                    models.TextField(
                        help_text="Why this row is correct. A check-only source may never be the sole basis for an override: a discrepancy it surfaces is resolved by independent re-derivation from OSM, federal, or CC0 inputs."
                    ),
                ),
                ("approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "override",
                "indexes": [
                    models.Index(
                        fields=["osm_way_id", "approved"],
                        name="override_osm_way_aa50c8_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CachedMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discord_user_id", models.BigIntegerField()),
                ("role_ids", models.JSONField(default=list)),
                ("last_confirmed", models.DateTimeField()),
                ("pending", models.BooleanField(default=False)),
                ("timed_out_until", models.DateTimeField(blank=True, null=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="core.configuredguild",
                    ),
                ),
            ],
            options={
                "db_table": "cached_membership",
                "indexes": [
                    models.Index(
                        fields=["discord_user_id"],
                        name="cached_memb_discord_f9689e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("discord_user_id", "guild"),
                        name="one_membership_row_per_guild",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RoleMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_id", models.BigIntegerField()),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("reviewer", "Reviewer"),
                            ("guild_admin", "Guild admin"),
                            ("instance_admin", "Instance admin"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="core.configuredguild",
                    ),
                ),
            ],
            options={
                "db_table": "role_mapping",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("guild", "role_id"), name="one_mapping_per_role"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("issued_epoch", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "app_session",
                "indexes": [
                    models.Index(fields=["user"], name="app_session_user_id_40fd68_idx")
                ],
            },
        ),
    ]
