# Generated by Django 5.2.17 on 2026-09-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jurisdiction",
            name="layer",
            field=models.CharField(
                choices=[
                    ("state", "State or district"),
                    ("police", "Police authority"),
                    ("row", "Right-of-way owner"),
                    ("manager", "Park or trail manager"),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="ScheduledRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task", models.CharField(max_length=64)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("succeeded", models.BooleanField(default=False)),
                ("detail", models.TextField(blank=True)),
            ],
            options={
                "db_table": "scheduled_run",
                "indexes": [
                    models.Index(
                        fields=["task", "-started_at"],
                        name="scheduled_r_task_c6da0c_idx",
                    )
                ],
            },
        ),
    ]
