# Generated by Django 5.2.17 on 2026-09-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_jurisdiction_layer_scheduledrun"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="created_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="session",
            name="last_seen_at",
            field=models.DateTimeField(),
        ),
    ]
