# Generated by Django 5.2.17 on 2026-09-15 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_explicit_session_timestamps"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("at", models.DateTimeField(auto_now_add=True)),
                ("action", models.CharField(max_length=32)),
                ("model", models.CharField(max_length=64)),
                ("object_id", models.CharField(blank=True, max_length=64)),
                (
                    "outcome",
                    models.CharField(
                        choices=[("allowed", "Allowed"), ("refused", "Refused")],
                        max_length=16,
                    ),
                ),
                ("detail", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_log",
                "indexes": [
                    models.Index(fields=["-at"], name="audit_log_at_078962_idx"),
                    models.Index(
                        fields=["actor", "-at"], name="audit_log_actor_i_ff920d_idx"
                    ),
                    models.Index(
                        fields=["model", "-at"], name="audit_log_model_bbbf63_idx"
                    ),
                ],
            },
        ),
    ]
