# Generated by Django 5.2.17 on 2026-09-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_audit_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValhallaUpstream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variant", models.CharField(max_length=16, unique=True)),
                ("url", models.CharField(max_length=200)),
                ("build_id", models.CharField(blank=True, max_length=32)),
                ("previous_build_id", models.CharField(blank=True, max_length=32)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "valhalla_upstream",
            },
        ),
        migrations.AlterModelOptions(
            name="bordercrossing",
            options={"managed": False},
        ),
        # Marking the model unmanaged leaves the managed table behind, and with
        # `public` first on the search path that orphan would shadow the
        # promoted copy in the live schema forever. Dropped explicitly, and
        # schema-qualified on purpose: this is the one migration statement that
        # must never resolve to the swapped schema. The rows are derived state a
        # rebuild rewrites, so nothing is migrated across.
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS public.border_crossing",
            reverse_sql="""
                CREATE TABLE public.border_crossing (
                    id bigserial PRIMARY KEY,
                    node_id bigint NOT NULL UNIQUE,
                    location geometry(Point, 4326) NOT NULL,
                    osm_way_id bigint NOT NULL,
                    state_a varchar(2) NOT NULL,
                    state_b varchar(2) NOT NULL
                );
                CREATE INDEX border_cros_osm_way_efb172_idx
                    ON public.border_crossing (osm_way_id);
            """,
        ),
        migrations.CreateModel(
            name="DriftReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("build_id", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("segments_before", models.IntegerField()),
                ("segments_after", models.IntegerField()),
                ("segments_lost", models.IntegerField()),
                ("segments_added", models.IntegerField()),
                ("segments_regraded", models.IntegerField()),
                ("crossings_before", models.IntegerField()),
                ("crossings_after", models.IntegerField()),
                ("unresolved_anchors", models.IntegerField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "db_table": "drift_report",
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="drift_repor_created_bee380_idx"
                    )
                ],
            },
        ),
    ]
