# Generated by Django 5.2.17 on 2026-09-17 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_swap_settings_and_staged_crossings"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstanceAdminListing",
            fields=[],
            options={
                "verbose_name": "instance admin",
                "verbose_name_plural": "instance admins",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.user",),
        ),
        migrations.AddField(
            model_name="auditlogentry",
            name="actor_user_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PendingInstanceAdminRemoval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_by_user_id", models.BigIntegerField(blank=True, null=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("effective_at", models.DateTimeField()),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_admin_removals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_instance_admin_removal",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pending_instance_admin_removal",
                "indexes": [
                    models.Index(
                        fields=["effective_at"], name="pending_ins_effecti_adf374_idx"
                    )
                ],
            },
        ),
    ]
