# Generated by Django 5.2.17 on 2026-09-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bootstrap_claim'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=32)),
                ('client', models.CharField(max_length=64)),
                ('window_start', models.DateTimeField()),
                ('hits', models.IntegerField()),
            ],
            options={
                'db_table': 'rate_limit_window',
                'indexes': [models.Index(fields=['window_start'], name='rate_limit_window_start')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'client'), name='rate_limit_window_client')],
            },
        ),
    ]
