# Generated by Django 5.2.17 on 2026-10-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_segment_mtb_only_walk_bike'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeshareFeedCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=16, unique=True)),
                ('payload', models.JSONField(null=True)),
                ('fetched_at', models.DateTimeField(null=True)),
                ('failed_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'bikeshare_feed_cache',
            },
        ),
    ]
