"""GET /tiles/stress/{z}/{x}/{y}.pbf: the traffic-stress overlay, as vector tiles.

The SHARED API CONTRACT: a Mapbox Vector Tile with one layer, "stress", whose
features come from the live segment table with the properties "tier" (1-4),
"trail" and "unpaved"; served for zooms 10 to 16, an empty tile (200, no
bytes) outside the coverage box or outside those zooms, generated by PostGIS's
ST_AsMVT, with Cache-Control, and no sign-in. What stands in for the sign-in is
the per-address limit (`core.ratelimit.TILES`), counted before anything else.

Tiles are drawn at three levels of detail, because the table has 1,357,800
segments and a tile holding every one of them is useless at region scale:
measured on the first promoted build, the z10 tile over downtown DC held
228,854 of them in 6.0 MB and took 3.5 s, and the z12 tile 47,392 in 1.2 MB.

- `TRAILS`, z10 to ROAD_STRESS_MIN_ZOOM - 1: the traffic-free paths and
  trails and nothing else (`pipeline.schema.trails_predicate`: what
  `routemaker.facility` calls a path, and the protected ways that are trails
  of their own beside a road). The owner, 2026-09-28: "It looks way too busy
  zoomed out though." and "Zoomed out just show the trails." (OWNER-DECISIONS
  64, 65), and 2026-09-29: "Show roadside trails (Recommended)" (66).
- `STREETS`, from ROAD_STRESS_MIN_ZOOM to z13: the full stress colours, every
  segment except the sidewalk class (footways, pedestrian ways, steps;
  `SIDEWALK_CLASS_HIGHWAY`), which in DC is a second copy of the street grid
  beside the first.
- `FULL`, z14-16: every segment, one feature each. The map asks for nothing
  past z14 - it draws z15-16 from the z14 tile (`STRESS_ZOOMS.max` in the front
  end's mapStyle.ts) - so z14 is the deepest zoom drawn ahead; z15-16 are
  still served, for the contract, and drawn on request.

At the first two levels a tile carries one feature per distinct (tier, trail,
unpaved, facility) - every segment of a class collected into one multi-line
and simplified to the tile's grid - so the size is the drawn geometry and not
a per-segment overhead; the properties a feature carries are still exactly its
segments'. What each level selects is written once, in `pipeline.schema`,
where the overview's partial GiST index is created with the zoomed-out
predicate, so the planner can prove the index applies.

Caching: the tiles change only when a rebuild promotes a new segment table, and
the promoted table is a new relation each time, so the ETag is that table's
oid with this module's format version. A client that already has a tile gets
a 304 without the tile being drawn again, and a tile drawn once is kept in
`core.tile_cache`, so a request
for one is a lookup, not a draw. Every tile the map asks for, z10 to z14 over
the coverage box, is drawn ahead after every promotion (the owner, 2026-09-28:
"It takes a very long time to load those roads.", where it felt slow: "Zoomed
in (street level)"; OWNER-DECISIONS 63).

A draw (a tile not in the cache) takes an in-flight slot
(`ratelimit.TILES_IN_FLIGHT`) and runs under DRAW_TIMEOUT_MS: well under the
swap's 3 s lock timeout, so a promotion waiting for its lock behind a tile
draw normally takes it on the first attempt, and short enough that the slots
cannot hold workers for long. It is not a hard bound: PostgreSQL checks for the
cancel between steps, and one cold draw on a busy host was seen to end at
5.46 s. The swap's retries (five attempts) are what cover that. A draw
refused a slot, or cut off by the timeout, is answered 429 or 503 with
Retry-After, which the front end waits out.

Coverage: a tile straddling the edge of `settings.COVERAGE_BBOX` is drawn from
its segments clipped to the box, so nothing is drawn in the map's grey area.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

from django.conf import settings
from django.db import OperationalError, connection, transaction
from django.http import HttpResponse, JsonResponse
from django.utils.cache import patch_cache_control
from django.utils.http import parse_etags
from django.views.decorators.http import require_http_methods

from pipeline.schema import (
    FACILITY_COLUMN,
    STREETS_PREDICATE,
    TRAIL_NETWORK_FACILITY,
    keeping_facilities,
    trails_predicate,
    validate_schema_name,
)

from . import ratelimit, tile_cache

LAYER = "stress"
MIN_ZOOM = 10
MAX_ZOOM = 16

# THE ZOOM THE ROADS' STRESS COLOURS START AT. Further out the overlay draws
# only the traffic-free paths (the owner, 2026-09-28: "Zoomed out just show
# the trails."; the orchestrator's default of z13, neighbourhood scale, which
# the owner may move). The front end's legend says so from its own copy,
# `STRESS_ZOOMS.roads` in frontend/src/lib/mapStyle.ts, which a test holds
# equal to this: change both. Between MIN_ZOOM + 1 and FULL_MIN_ZOOM.
ROAD_STRESS_MIN_ZOOM = 13

# Where a tile stops merging a class's segments and carries each one.
FULL_MIN_ZOOM = 14
# ST_TileEnvelope's own ceiling; a larger zoom is not a tile address.
MAX_ADDRESSABLE_ZOOM = 30

CONTENT_TYPE = "application/vnd.mapbox-vector-tile"

# Bumped whenever what a tile holds changes for the same table, so a client's
# cached tiles - and the tile cache's rows (core.tile_cache) - are not served
# as current against a different encoding. 3: the zoomed-out tiles became the
# paths and trails alone (OWNER-DECISIONS 65, 66), for a live table whose oid the deploy
# does not change.
FORMAT_VERSION = 3

# An hour: a rebuild is weekly and a stale hour after one is harmless, and a
# revalidation after that is a 304 that draws nothing.
MAX_AGE_S = 3600

# How long a tile draw on request may run. The swap takes its lock with a 3 s
# lock_timeout (pipeline.swap.DEFAULT_LOCK_TIMEOUT_MS) and waits behind any
# draw holding the table, so a draw must end well inside that. Every tile the
# map asks for is drawn ahead, so a draw on request is one the pre-draw has not
# reached yet (or a z15-16 tile, which the map does not ask for).
DRAW_TIMEOUT_MS = 2000

# The pre-draw's own limit per tile, well past the dearest z14 tile over
# downtown DC. It runs right after the swap, not during one.
PREDRAW_TIMEOUT_MS = 20_000

# What a refused or cut-off draw asks the client to wait.
RETRY_AFTER_S = 1

# EPSG:3857's full width, in metres.
WORLD_M = 2 * math.pi * 6378137


@dataclass(frozen=True)
class Level:
    name: str
    min_zoom: int
    extent: int
    # Tile units drawn past each edge, so a line's casing is not cut at it.
    buffer: int
    # SQL over the segment table's columns, or None for every row.
    where: str | None
    # One feature per class, simplified, rather than one per segment.
    merged: bool
    # Only the paths and trails (`pipeline.schema.trails_predicate`), in place of `where`.
    trails_only: bool = False


TRAILS = Level("trails", MIN_ZOOM, 4096, 32, None, merged=True, trails_only=True)
STREETS = Level("streets", ROAD_STRESS_MIN_ZOOM, 4096, 32, STREETS_PREDICATE, merged=True)
FULL = Level("full", FULL_MIN_ZOOM, 4096, 64, None, merged=False)
LEVELS = (FULL, STREETS, TRAILS)


def level_for(z: int) -> Level:
    return next(level for level in LEVELS if z >= level.min_zoom)


def tile_bounds(z: int, x: int, y: int) -> tuple[float, float, float, float]:
    """(west, south, east, north) in degrees."""
    n = 2**z

    def lat(row: int) -> float:
        return math.degrees(math.atan(math.sinh(math.pi * (1 - 2 * row / n))))

    return x / n * 360 - 180, lat(y + 1), (x + 1) / n * 360 - 180, lat(y)


def outside_coverage(z: int, x: int, y: int) -> bool:
    west, south, east, north = tile_bounds(z, x, y)
    c_west, c_south, c_east, c_north = settings.COVERAGE_BBOX
    return east < c_west or west > c_east or north < c_south or south > c_north


def straddles_coverage(z: int, x: int, y: int, margin: float) -> bool:
    """Whether the tile, with `margin` of its width drawn past each edge,
    reaches past the coverage box - and so has to be clipped to it."""
    west, south, east, north = tile_bounds(z, x, y)
    dx, dy = (east - west) * margin, (north - south) * margin
    c_west, c_south, c_east, c_north = settings.COVERAGE_BBOX
    return west - dx < c_west or east + dx > c_east or south - dy < c_south or north + dy > c_north


# Each feature's properties, as {tile property: segment column}: the one place
# that says what a tile carries. A value is carried as the column holds it, so
# a new tier value reaches the tile unchanged; a new property is a new entry
# here (and, if the zoomed-out levels should keep it, a term in
# pipeline.schema's predicates). A null is left out of the feature rather than
# sent - an unknown surface is not "paved".
PROPERTIES = {"tier": "stress_tier", "trail": "is_trail_class", "unpaved": "is_unpaved"}

# Properties carried only from a live table that has the column: the bike
# facility (path, protected, lane, none), which the rebuild writes from
# `routemaker.facility`, and a table promoted before it has no such column. Where it is
# there, the street-zoom level also keeps the paths and protected lanes
# (`pipeline.schema.keeping_facilities`) and the zoomed-out one draws its
# paths. Where it is not, a stand-in is carried in its place (`FALLBACKS`)
# and the zoomed-out paths are the ones that stand-in calls a path.
OPTIONAL_PROPERTIES = {"facility": FACILITY_COLUMN}

# What an optional property is drawn from on a table without its column: the
# facility is derived from the trail network (an off-road path, or nothing),
# so the trails carry the path's rails at every zoom before the column exists.
FALLBACKS = {"facility": TRAIL_NETWORK_FACILITY}

_MERGED = """
WITH bounds AS (SELECT ST_TileEnvelope(%(z)s, %(x)s, %(y)s) AS env),
features AS (
    SELECT {columns},
           ST_AsMVTGeom(
               ST_Simplify(ST_Collect(ST_Transform({geometry}, 3857)), %(unit)s),
               bounds.env, %(extent)s, %(buffer)s, true
           ) AS geom
    FROM {table} AS s, bounds
    WHERE s.geometry && ST_Transform(
              ST_TileEnvelope(%(z)s, %(x)s, %(y)s, margin => %(margin)s), 4326)
      {coverage}
      AND {where}
    GROUP BY {group_by}, bounds.env
)
SELECT '{table}'::regclass::oid,
       (SELECT ST_AsMVT(features.*, '{layer}', %(extent)s, 'geom') FROM features)
"""

_PER_SEGMENT = """
WITH bounds AS (SELECT ST_TileEnvelope(%(z)s, %(x)s, %(y)s) AS env),
features AS (
    SELECT {columns},
           ST_AsMVTGeom(ST_Transform({geometry}, 3857), bounds.env, %(extent)s, %(buffer)s, true)
               AS geom
    FROM {table} AS s, bounds
    WHERE s.geometry && ST_Transform(
              ST_TileEnvelope(%(z)s, %(x)s, %(y)s, margin => %(margin)s), 4326)
      {coverage}
      AND {where}
)
SELECT '{table}'::regclass::oid,
       (SELECT ST_AsMVT(features.*, '{layer}', %(extent)s, 'geom') FROM features)
"""


def _table() -> str:
    # The schema name comes from settings and is validated the way every DDL
    # naming it is; an identifier cannot be a query parameter.
    return f"{validate_schema_name(settings.SEGMENT_SCHEMA_LIVE)}.segment"


# The coverage box, as the clipped query reads it from its parameters.
_COVERAGE_BOX = "ST_MakeEnvelope(%(c_west)s, %(c_south)s, %(c_east)s, %(c_north)s, 4326)"


def tile_sql(level: Level, optional: frozenset[str] = frozenset(), clip: bool = False) -> str:
    """The level's query, carrying the optional columns in `optional` too, and
    with `clip`, drawing only what lies inside the coverage box."""
    template = _MERGED if level.merged else _PER_SEGMENT
    carried = {name: f"s.{column}" for name, column in PROPERTIES.items()}
    for name, column in OPTIONAL_PROPERTIES.items():
        if column in optional:
            carried[name] = f"s.{column}"
        elif name in FALLBACKS:
            carried[name] = FALLBACKS[name]
    has_facility = FACILITY_COLUMN in optional
    if level.trails_only:
        where = trails_predicate(has_facility)
    else:
        where = level.where or "true"
        if level.where and has_facility:
            where = keeping_facilities(where)
    return template.format(
        table=_table(),
        where=where,
        geometry=f"ST_ClipByBox2D(s.geometry, {_COVERAGE_BOX})" if clip else "s.geometry",
        coverage=f"AND s.geometry && {_COVERAGE_BOX}" if clip else "",
        layer=LAYER,
        columns=", ".join(f"{expression} AS {name}" for name, expression in carried.items()),
        group_by=", ".join(carried.values()),
    )


class DrawTimedOut(Exception):
    """A tile draw ran past its statement timeout and was cancelled."""


def render(
    z: int,
    x: int,
    y: int,
    optional: frozenset[str] = frozenset(),
    timeout_ms: int | None = None,
) -> tuple[int, bytes]:
    """(the live table's oid, the tile's bytes) for a tile inside the zooms
    served, drawn under a `timeout_ms` statement timeout (DRAW_TIMEOUT_MS if
    none is given)."""
    if timeout_ms is None:
        timeout_ms = DRAW_TIMEOUT_MS
    level = level_for(z)
    c_west, c_south, c_east, c_north = settings.COVERAGE_BBOX
    params = {
        "c_west": c_west,
        "c_south": c_south,
        "c_east": c_east,
        "c_north": c_north,
        "z": z,
        "x": x,
        "y": y,
        "extent": level.extent,
        "buffer": level.buffer,
        "margin": level.buffer / level.extent,
        # One tile unit, in metres of EPSG:3857: finer detail is not drawn.
        "unit": WORLD_M / 2**z / level.extent,
    }
    clip = straddles_coverage(z, x, y, level.buffer / level.extent)
    try:
        with transaction.atomic(), connection.cursor() as cursor:
            cursor.execute("SELECT set_config('statement_timeout', %s, true)", [str(timeout_ms)])
            cursor.execute(tile_sql(level, optional, clip), params)
            oid, tile = cursor.fetchone()
    except OperationalError as error:
        if getattr(error.__cause__, "sqlstate", None) == "57014":  # query_canceled
            raise DrawTimedOut(f"tile {z}/{x}/{y} ran past {timeout_ms} ms") from error
        raise
    return oid, bytes(tile or b"")


def live_table() -> tuple[int | None, frozenset[str]]:
    """The live table's oid, or None before any build, and which of the
    optional columns it has."""
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT t.oid, ARRAY(SELECT attname::text FROM pg_attribute WHERE attrelid = t.oid "
            "AND attname = ANY(%s) AND NOT attisdropped) "
            "FROM (SELECT to_regclass(%s)::oid AS oid) AS t",
            [list(OPTIONAL_PROPERTIES.values()), _table()],
        )
        oid, columns = cursor.fetchone()
    return oid, frozenset(columns or ())


def etag_for(oid: int, optional: frozenset[str] = frozenset()) -> str:
    # Weak: the same table always draws the same features, but not always the
    # same bytes - ST_AsMVT's feature and value order follows the scan's row
    # order, and two draws of one z14 tile measured 124,520 and 124,532 bytes.
    # A strong tag promises byte-identical bodies (RFC 9110 8.8.1). The
    # optional columns are in it because a column added to the live table in
    # place (the facility, by hand) changes the tiles but not the table's oid.
    carried = "".join(f"+{column}" for column in sorted(optional))
    return f'W/"stress-{oid}{carried}-v{FORMAT_VERSION}"'


def _matches(request, etag: str) -> bool:
    header = request.META.get("HTTP_IF_NONE_MATCH", "")
    if not header:
        return False
    # If-None-Match uses the weak comparison (RFC 9110 13.1.2): W/ or not,
    # the same opaque tag matches.
    tags = [tag.removeprefix("W/") for tag in parse_etags(header)]
    return "*" in tags or etag.removeprefix("W/") in tags


def _tile_response(body: bytes, status: int = 200, etag: str | None = None) -> HttpResponse:
    response = HttpResponse(body, status=status, content_type=CONTENT_TYPE)
    patch_cache_control(response, public=True, max_age=MAX_AGE_S)
    if etag is not None:
        response["ETag"] = etag
    return response


@require_http_methods(["GET", "HEAD"])
@ratelimit.rate_limited(ratelimit.TILES)
def stress_tile(request, z: int, x: int, y: int) -> HttpResponse:
    if z > MAX_ADDRESSABLE_ZOOM or x >= 2**z or y >= 2**z:
        response = JsonResponse({"error": "not a tile address"}, status=400)
        response["Cache-Control"] = "no-store"
        return response
    if not MIN_ZOOM <= z <= MAX_ZOOM or outside_coverage(z, x, y):
        return _tile_response(b"")
    oid, optional = live_table()
    if oid is None:
        # No build has been promoted: nothing to draw, and the front end hides
        # the overlay on a 404 rather than showing a legend for nothing.
        response = JsonResponse({"error": "no stress data has been built yet"}, status=404)
        response["Cache-Control"] = "no-store"
        return response
    etag = etag_for(oid, optional)
    if _matches(request, etag):
        return _tile_response(b"", status=304, etag=etag)
    cached = tile_cache.get(etag, z, x, y)
    if cached is not None:
        return _tile_response(cached, etag=etag)
    held, refusal = ratelimit.acquire(request, ratelimit.TILES_IN_FLIGHT)
    if refusal is not None:
        refusal["Cache-Control"] = "no-store"
        return refusal
    try:
        try:
            drawn_oid, body = render(z, x, y, optional)
        except DrawTimedOut:
            response = JsonResponse(
                {"error": "This part of the stress map is taking too long; try again shortly."},
                status=503,
            )
            response["Retry-After"] = str(RETRY_AFTER_S)
            response["Cache-Control"] = "no-store"
            return response
    finally:
        ratelimit.release(held)
    if drawn_oid == oid:
        # Not when a promotion landed between the lookup and the draw: this
        # body belongs to the new table, and its own requests will cache it.
        tile_cache.put(etag, z, x, y, body)
    return _tile_response(body, etag=etag_for(drawn_oid, optional))
