"""GET /tiles/stress/{z}/{x}/{y}.pbf: the traffic-stress overlay, as vector tiles.

The SHARED API CONTRACT: a Mapbox Vector Tile with one layer, "stress", whose
features come from the live segment table with the properties "tier" (1-4),
"trail" and "unpaved"; served for zooms 10 to 16, an empty tile (200, no
bytes) outside the coverage box or outside those zooms, generated by PostGIS's
ST_AsMVT, with Cache-Control, and no sign-in. What stands in for the sign-in is
the per-address limit (`core.ratelimit.TILES`), counted before anything else.

Tiles are drawn at three levels of detail, because the table has 1,357,800
segments and a tile holding every one of them is useless at region scale:
measured on the first promoted build, the z10 tile over downtown DC held
228,854 of them in 6.0 MB and took 3.5 s, and the z12 tile 47,392 in 1.2 MB.

- `OVERVIEW`, z10-11: the roads of LTS 3 and 4 and the trail network
  (cycleways, paths, bridleways, and footways designated for bicycles that
  are not sidewalks; `pipeline.schema.TRAIL_NETWORK_RULES`).
  Quiet streets and sidewalks are left out: at this scale they are a solid
  mesh over every street grid, and the question a zoomed-out map answers is
  where the busy roads and the trails are. The front end's legend says so.
- `STREETS`, z12-13: every segment except the sidewalk class (footways,
  pedestrian ways, steps; `SIDEWALK_CLASS_HIGHWAY`), which in DC is a second
  copy of the street grid beside the first.
- `FULL`, z14-16: every segment, one feature each.

At the first two levels a tile carries one feature per distinct (tier, trail,
unpaved) - every segment of a class collected into one multi-line and
simplified to the tile's grid - so the size is the drawn geometry and not a
per-segment overhead; the properties a feature carries are still exactly its
segments'. What each level selects is written once, in `pipeline.schema`,
where the overview's partial GiST index is created with the same predicate, so
the planner can prove the index applies (its scan of the z10 downtown tile
went from 285 ms to 7 ms).

Caching: the tiles change only when a rebuild promotes a new segment table, and
the promoted table is a new relation each time, so the ETag is that table's
oid with this module's format version. A client that already has a tile gets
a 304 without the tile being drawn again.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

from django.conf import settings
from django.db import connection
from django.http import HttpResponse, JsonResponse
from django.utils.cache import patch_cache_control
from django.utils.http import parse_etags
from django.views.decorators.http import require_http_methods

from pipeline.schema import (
    FACILITY_COLUMN,
    OVERVIEW_PREDICATE,
    STREETS_PREDICATE,
    TRAIL_NETWORK_FACILITY,
    keeping_facilities,
    validate_schema_name,
)

from . import ratelimit

LAYER = "stress"
MIN_ZOOM = 10
MAX_ZOOM = 16
# ST_TileEnvelope's own ceiling; a larger zoom is not a tile address.
MAX_ADDRESSABLE_ZOOM = 30

CONTENT_TYPE = "application/vnd.mapbox-vector-tile"

# Bumped whenever what a tile holds changes for the same table, so a client's
# cached tiles are not revalidated as current against a different encoding.
FORMAT_VERSION = 2

# An hour: a rebuild is weekly and a stale hour after one is harmless, and a
# revalidation after that is a 304 that draws nothing.
MAX_AGE_S = 3600

# EPSG:3857's full width, in metres.
WORLD_M = 2 * math.pi * 6378137


@dataclass(frozen=True)
class Level:
    name: str
    min_zoom: int
    extent: int
    # Tile units drawn past each edge, so a line's casing is not cut at it.
    buffer: int
    # SQL over the segment table's columns, or None for every row.
    where: str | None
    # One feature per class, simplified, rather than one per segment.
    merged: bool


OVERVIEW = Level("overview", MIN_ZOOM, 2048, 16, OVERVIEW_PREDICATE, merged=True)
STREETS = Level("streets", 12, 4096, 32, STREETS_PREDICATE, merged=True)
FULL = Level("full", 14, 4096, 64, None, merged=False)
LEVELS = (FULL, STREETS, OVERVIEW)


def level_for(z: int) -> Level:
    return next(level for level in LEVELS if z >= level.min_zoom)


def tile_bounds(z: int, x: int, y: int) -> tuple[float, float, float, float]:
    """(west, south, east, north) in degrees."""
    n = 2**z

    def lat(row: int) -> float:
        return math.degrees(math.atan(math.sinh(math.pi * (1 - 2 * row / n))))

    return x / n * 360 - 180, lat(y + 1), (x + 1) / n * 360 - 180, lat(y)


def outside_coverage(z: int, x: int, y: int) -> bool:
    west, south, east, north = tile_bounds(z, x, y)
    c_west, c_south, c_east, c_north = settings.COVERAGE_BBOX
    return east < c_west or west > c_east or north < c_south or south > c_north


# Each feature's properties, as {tile property: segment column}: the one place
# that says what a tile carries. A value is carried as the column holds it, so
# a new tier value reaches the tile unchanged; a new property is a new entry
# here (and, if the zoomed-out levels should keep it, a term in
# pipeline.schema's predicates). A null is left out of the feature rather than
# sent - an unknown surface is not "paved".
PROPERTIES = {"tier": "stress_tier", "trail": "is_trail_class", "unpaved": "is_unpaved"}

# Properties carried only from a live table that has the column: the bike
# facility (path, protected, lane, none) arrives with the routing lane's
# change, and a table promoted before it has no such column. Where it is
# there, the zoomed-out levels also keep the paths and protected lanes
# (`pipeline.schema.keeping_facilities`). Where it is not, a stand-in is
# carried in its place (`FALLBACKS`).
OPTIONAL_PROPERTIES = {"facility": FACILITY_COLUMN}

# What an optional property is drawn from on a table without its column: the
# facility is derived from the trail network (an off-road path, or nothing),
# so the trails carry the path's rails at every zoom before the column exists.
FALLBACKS = {"facility": TRAIL_NETWORK_FACILITY}

_MERGED = """
WITH bounds AS (SELECT ST_TileEnvelope(%(z)s, %(x)s, %(y)s) AS env),
features AS (
    SELECT {columns},
           ST_AsMVTGeom(
               ST_Simplify(ST_Collect(ST_Transform(s.geometry, 3857)), %(unit)s),
               bounds.env, %(extent)s, %(buffer)s, true
           ) AS geom
    FROM {table} AS s, bounds
    WHERE s.geometry && ST_Transform(
              ST_TileEnvelope(%(z)s, %(x)s, %(y)s, margin => %(margin)s), 4326)
      AND {where}
    GROUP BY {group_by}, bounds.env
)
SELECT '{table}'::regclass::oid,
       (SELECT ST_AsMVT(features.*, '{layer}', %(extent)s, 'geom') FROM features)
"""

_PER_SEGMENT = """
WITH bounds AS (SELECT ST_TileEnvelope(%(z)s, %(x)s, %(y)s) AS env),
features AS (
    SELECT {columns},
           ST_AsMVTGeom(ST_Transform(s.geometry, 3857), bounds.env, %(extent)s, %(buffer)s, true)
               AS geom
    FROM {table} AS s, bounds
    WHERE s.geometry && ST_Transform(
              ST_TileEnvelope(%(z)s, %(x)s, %(y)s, margin => %(margin)s), 4326)
      AND {where}
)
SELECT '{table}'::regclass::oid,
       (SELECT ST_AsMVT(features.*, '{layer}', %(extent)s, 'geom') FROM features)
"""


def _table() -> str:
    # The schema name comes from settings and is validated the way every DDL
    # naming it is; an identifier cannot be a query parameter.
    return f"{validate_schema_name(settings.SEGMENT_SCHEMA_LIVE)}.segment"


def tile_sql(level: Level, optional: frozenset[str] = frozenset()) -> str:
    """The level's query, carrying the optional columns in `optional` too."""
    template = _MERGED if level.merged else _PER_SEGMENT
    carried = {name: f"s.{column}" for name, column in PROPERTIES.items()}
    for name, column in OPTIONAL_PROPERTIES.items():
        if column in optional:
            carried[name] = f"s.{column}"
        elif name in FALLBACKS:
            carried[name] = FALLBACKS[name]
    where = level.where or "true"
    if level.where and FACILITY_COLUMN in optional:
        where = keeping_facilities(where)
    return template.format(
        table=_table(),
        where=where,
        layer=LAYER,
        columns=", ".join(f"{expression} AS {name}" for name, expression in carried.items()),
        group_by=", ".join(carried.values()),
    )


def render(z: int, x: int, y: int, optional: frozenset[str] = frozenset()) -> tuple[int, bytes]:
    """(the live table's oid, the tile's bytes) for a tile inside the zooms served."""
    level = level_for(z)
    params = {
        "z": z,
        "x": x,
        "y": y,
        "extent": level.extent,
        "buffer": level.buffer,
        "margin": level.buffer / level.extent,
        # One tile unit, in metres of EPSG:3857: finer detail is not drawn.
        "unit": WORLD_M / 2**z / level.extent,
    }
    with connection.cursor() as cursor:
        cursor.execute(tile_sql(level, optional), params)
        oid, tile = cursor.fetchone()
    return oid, bytes(tile or b"")


def live_table() -> tuple[int | None, frozenset[str]]:
    """The live table's oid, or None before any build, and which of the
    optional columns it has."""
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT t.oid, ARRAY(SELECT attname::text FROM pg_attribute WHERE attrelid = t.oid "
            "AND attname = ANY(%s) AND NOT attisdropped) "
            "FROM (SELECT to_regclass(%s)::oid AS oid) AS t",
            [list(OPTIONAL_PROPERTIES.values()), _table()],
        )
        oid, columns = cursor.fetchone()
    return oid, frozenset(columns or ())


def etag_for(oid: int, optional: frozenset[str] = frozenset()) -> str:
    # Weak: the same table always draws the same features, but not always the
    # same bytes - ST_AsMVT's feature and value order follows the scan's row
    # order, and two draws of one z14 tile measured 124,520 and 124,532 bytes.
    # A strong tag promises byte-identical bodies (RFC 9110 8.8.1). The
    # optional columns are in it because a column added to the live table in
    # place (the facility, by hand) changes the tiles but not the table's oid.
    carried = "".join(f"+{column}" for column in sorted(optional))
    return f'W/"stress-{oid}{carried}-v{FORMAT_VERSION}"'


def _matches(request, etag: str) -> bool:
    header = request.META.get("HTTP_IF_NONE_MATCH", "")
    if not header:
        return False
    # If-None-Match uses the weak comparison (RFC 9110 13.1.2): W/ or not,
    # the same opaque tag matches.
    tags = [tag.removeprefix("W/") for tag in parse_etags(header)]
    return "*" in tags or etag.removeprefix("W/") in tags


def _tile_response(body: bytes, status: int = 200, etag: str | None = None) -> HttpResponse:
    response = HttpResponse(body, status=status, content_type=CONTENT_TYPE)
    patch_cache_control(response, public=True, max_age=MAX_AGE_S)
    if etag is not None:
        response["ETag"] = etag
    return response


@require_http_methods(["GET", "HEAD"])
@ratelimit.rate_limited(ratelimit.TILES)
def stress_tile(request, z: int, x: int, y: int) -> HttpResponse:
    if z > MAX_ADDRESSABLE_ZOOM or x >= 2**z or y >= 2**z:
        response = JsonResponse({"error": "not a tile address"}, status=400)
        response["Cache-Control"] = "no-store"
        return response
    if not MIN_ZOOM <= z <= MAX_ZOOM or outside_coverage(z, x, y):
        return _tile_response(b"")
    oid, optional = live_table()
    if oid is None:
        # No build has been promoted: nothing to draw, and the front end hides
        # the overlay on a 404 rather than showing a legend for nothing.
        response = JsonResponse({"error": "no stress data has been built yet"}, status=404)
        response["Cache-Control"] = "no-store"
        return response
    etag = etag_for(oid, optional)
    if _matches(request, etag):
        return _tile_response(b"", status=304, etag=etag)
    oid, body = render(z, x, y, optional)
    return _tile_response(body, etag=etag_for(oid, optional))
