"""GET /tiles/stress/{z}/{x}/{y}.pbf: the traffic-stress overlay, as vector tiles.

The SHARED API CONTRACT: a Mapbox Vector Tile with one layer, "stress", whose
features come from the live segment table with the properties "tier" (1-4),
"trail" and "unpaved"; served for zooms 10 to 16, an empty tile (200, no
bytes) outside the coverage box or outside those zooms, generated by PostGIS's
ST_AsMVT, with Cache-Control, and no sign-in. What stands in for the sign-in is
the per-address limit (`core.ratelimit.TILES`), counted before anything else.

Tiles are drawn at three levels of detail, because the table has 1,357,800
segments and a tile holding every one of them is useless at region scale:
measured on the first promoted build, the z10 tile over downtown DC held
228,854 of them in 6.0 MB and took 3.5 s, and the z12 tile 47,392 in 1.2 MB.

The owner, 2026-09-29: "Zoom less than 12, show just bike paths and the
metro/MARC. 12 and 13, show LTS 3+, 14+ show show the quiet streets."
(OWNER-DECISIONS 73; "Zoomed out just show the trails." before it, 65, and
"Show roadside trails (Recommended)", 66). Zoom 12-13 changed on 2026-10-05
(391): "I'm more concerned with the places to ride than the places not to." The
busy roads and their junction markers now wait for zoom 14, and z12-13 is the
RIDE LAYER below, on a table that has the column it reads:

- `TRAILS` and `TRAILS_NEAR`, z10 and z11 (up to BUSY_ROADS_MIN_ZOOM - 1): the
  traffic-free paths and trails and nothing else (`pipeline.schema.trails_predicate`:
  what `routemaker.facility` calls a path, the protected ways that are trails of
  their own beside a road, and the roads closed to cars at set times, for
  those times), and of those only the long ones: "Also zoomed out, can we stick
  to mostly the longer trails, it's getting messy." (OWNER-DECISIONS 375,
  2026-10-04). A way is long when it is on a regional-or-larger bicycle route
  or a long walking route (not a local one: OWNER-DECISIONS 377) or in a named
  run of trail long enough (`pipeline.schema.long_trails_predicate`), with a
  higher bar for an unpaved way and a higher bar again at z10 than at z11; a
  road closed to cars at set times stays whatever its length (377). The rail
  stations draw over them from the front end.
- `RIDE_LAYER`, from RIDE_LAYER_MIN_ZOOM to QUIET_STREETS_MIN_ZOOM - 1, "where
  to ride" (OWNER-DECISIONS 391): no road at LTS 3 or above is drawn. It holds the
  long and connected traffic-free paths (a connected network of at least
  RIDE_PATH_RUN_MI, which drops the short isolated stubs, and no mountain-bike
  trail), the calm roads worth a long ride (402, 402a: a continuous run of LTS 1 and 2
  road of at least RIDE_ROAD_RUN_MI with no junction with a road at LTS 3 or above,
  `pipeline.calm_roads`) and the roads closed to cars at set times
  (`pipeline.schema.ride_layer_predicate`, on `calm_run_m`, which the rebuild writes).
- `BUSY`, the same zooms on a table without the `calm_run_m` column, which draws what
  z12-13 drew before 391: the paths and trails and the roads at LTS 3 and above - Avoid
  and the expressways included (`pipeline.schema.busy_predicate`). The map draws them
  faint there (the owner: "The high LTS roads aren't that important because you aren't
  going to route around them.", "Show them faintly", then "Make solid at 14";
  OWNER-DECISIONS 76, 77). A data rebuild adds the column; nothing else does.
- `FULL`, from QUIET_STREETS_MIN_ZOOM: every segment, one feature each, the busy
  roads, the quiet streets and footways with the rest. The map asks for nothing past z14
  - it draws z15-16 from the z14 tile (`STRESS_ZOOMS.max` in the front end's
  mapStyle.ts) - so z14 is the deepest zoom drawn ahead; z15-16 are still
  served, for the contract, and drawn on request.

At the first two levels a tile carries one feature per distinct (tier, trail,
unpaved, facility) - every segment of a class collected into one multi-line
and simplified to the tile's grid - so the size is the drawn geometry and not
a per-segment overhead; the properties a feature carries are still exactly its
segments'. What each level selects is written once, in `pipeline.schema`,
where the overview's partial GiST index is created with the zoomed-out
predicate, so the planner can prove the index applies.

Caching: the tiles change only when a rebuild promotes a new segment table, and
the promoted table is a new relation each time, so the ETag is that table's
oid with this module's format version. A client that already has a tile gets
a 304 without the tile being drawn again, and a tile drawn once is kept in
`core.tile_cache`, so a request
for one is a lookup, not a draw. Every tile the map asks for, z10 to z14 over
the coverage box, is drawn ahead after every promotion (the owner, 2026-09-28:
"It takes a very long time to load those roads.", where it felt slow: "Zoomed
in (street level)"; OWNER-DECISIONS 63).

A draw (a tile not in the cache) takes an in-flight slot
(`ratelimit.TILES_IN_FLIGHT`) and runs under DRAW_TIMEOUT_MS: well under the
swap's 3 s lock timeout, so a promotion waiting for its lock behind a tile
draw normally takes it on the first attempt, and short enough that the slots
cannot hold workers for long. It is not a hard bound: PostgreSQL checks for the
cancel between steps, and one cold draw on a busy host was seen to end at
5.46 s. The swap's retries (five attempts) are what cover that. A draw
refused a slot, or cut off by the timeout, is answered 429 or 503 with
Retry-After, which the front end waits out.

Coverage: a tile straddling the edge of `settings.COVERAGE_BBOX` is drawn from
its segments clipped to the box, so nothing is drawn in the map's grey area.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

from django.conf import settings
from django.db import OperationalError, connection, transaction
from django.http import HttpResponse, JsonResponse
from django.utils.cache import patch_cache_control
from django.utils.http import parse_etags
from django.views.decorators.http import require_http_methods

from pipeline.schema import (
    CALM_RUN_COLUMN,
    CAR_FREE_COLUMN,
    FACILITY_COLUMN,
    MAP_CLASS_COLUMN,
    MASS_WIDTH_COLUMN,
    MOTOR_ONLY_RULE,
    MTB_ONLY_COLUMN,
    ROADSIDE_COLUMN,
    ROUGH_COLUMN,
    SEPARATE_BIKEWAY_COLUMN,
    TRAIL_BRIDGE_COLUMN,
    TRAIL_NETWORK_FACILITY,
    TRAIL_ROUTE_COLUMN,
    TRAIL_RUN_COLUMN,
    Z10_LONG_TRAILS,
    Z11_LONG_TRAILS,
    LongTrails,
    busy_predicate,
    long_trails_predicate,
    ride_layer_predicate,
    trails_predicate,
    validate_schema_name,
)
from routemaker import flow

from . import ratelimit, tile_cache

LAYER = "stress"
MIN_ZOOM = 10
MAX_ZOOM = 16

# THE ZOOMS THE ROADS COME IN AT (the owner, 2026-09-29, OWNER-DECISIONS 73, and
# 2026-10-05, 391). Further out than RIDE_LAYER_MIN_ZOOM only the long traffic-free
# paths and trails; from it the ride layer, and no busy road; from
# QUIET_STREETS_MIN_ZOOM every segment: the roads at LTS 3 and above, the quiet
# streets (LTS 1-2) and the junction markers with them. (On a table without the
# ride layer's column the roads at LTS 3 and above come in at RIDE_LAYER_MIN_ZOOM,
# as they did.) The front end's legend says so from its own copies,
# `STRESS_ZOOMS.ride` and `STRESS_ZOOMS.quiet` in frontend/src/lib/mapStyle.ts,
# which a test holds equal to these: change both, and run the pre-draw.
RIDE_LAYER_MIN_ZOOM = 12
QUIET_STREETS_MIN_ZOOM = 14

# The long trails come in two grades below RIDE_LAYER_MIN_ZOOM (OWNER-DECISIONS
# 375): z10 keeps fewer than z11. This is a server-side detail the front end
# does not need, so it is not in STRESS_ZOOMS.
TRAILS_NEAR_MIN_ZOOM = 11

# ST_TileEnvelope's own ceiling; a larger zoom is not a tile address.
MAX_ADDRESSABLE_ZOOM = 30

CONTENT_TYPE = "application/vnd.mapbox-vector-tile"

# Bumped whenever what a tile holds changes for the same table, so a client's
# cached tiles - and the tile cache's rows (core.tile_cache) - are not served
# as current against a different encoding. 3: the zoomed-out tiles became the
# paths and trails alone (OWNER-DECISIONS 65, 66), for a live table whose oid the deploy
# does not change. 4: the busy roads at z12-13 and the quiet streets from z14
# (73), with the expressway and separate-bikeway properties. 5: z10-11 keep
# only the long trails (375). 6 was taken by two branches that never shipped on their own:
# the ride layer at z12-13, with no busy road, on a table with `calm_run_m` (391), and
# surface-unknown paths told apart by a missing `unpaved` (376); and the Mass Ride
# capacity, `rpm`, on a table that has the column (OWNER-DECISIONS 325-327, 387). 7: the
# rebuild bundle, which carries both, with the roadside trails' `roadside` (403) and
# NO-BIKE-PATHS' `mtb` and `rough` (290, 291).
FORMAT_VERSION = 7

# An hour: a rebuild is weekly and a stale hour after one is harmless, and a
# revalidation after that is a 304 that draws nothing.
MAX_AGE_S = 3600

# How long a tile draw on request may run. The swap takes its lock with a 3 s
# lock_timeout (pipeline.swap.DEFAULT_LOCK_TIMEOUT_MS) and waits behind any
# draw holding the table, so a draw must end well inside that. Every tile the
# map asks for is drawn ahead, so a draw on request is one the pre-draw has not
# reached yet (or a z15-16 tile, which the map does not ask for).
DRAW_TIMEOUT_MS = 2000

# The pre-draw's own limit per tile, well past the dearest z14 tile over
# downtown DC. It runs right after the swap, not during one.
PREDRAW_TIMEOUT_MS = 20_000

# What a refused or cut-off draw asks the client to wait.
RETRY_AFTER_S = 1

# EPSG:3857's full width, in metres.
WORLD_M = 2 * math.pi * 6378137


@dataclass(frozen=True)
class Level:
    name: str
    min_zoom: int
    extent: int
    # Tile units drawn past each edge, so a line's casing is not cut at it.
    buffer: int
    # SQL over the segment table's columns, or None for every row.
    where: str | None
    # One feature per class, simplified, rather than one per segment.
    merged: bool
    # The predicate drawn from `pipeline.schema`, by (has facility, has car_free),
    # in place of `where`: the trails', or the busy roads'.
    predicate: object = None
    # The bars for the long-trails rule (`pipeline.schema.long_trails_predicate`),
    # or None to keep every way the predicate selects. Applied only to a table
    # that has all three long-trail columns (LONG_TRAIL_COLUMNS); on one
    # without, today's tiles are drawn.
    long_trails: LongTrails | None = None


# The thresholds are the named constants in `pipeline.schema`, from
# OWNER-DECISIONS 375, 377, 378 and 380.
TRAILS = Level(
    "trails",
    MIN_ZOOM,
    4096,
    32,
    None,
    merged=True,
    predicate=trails_predicate,
    long_trails=Z10_LONG_TRAILS,
)
TRAILS_NEAR = Level(
    "trails-near",
    TRAILS_NEAR_MIN_ZOOM,
    4096,
    32,
    None,
    merged=True,
    predicate=trails_predicate,
    long_trails=Z11_LONG_TRAILS,
)
RIDE_LAYER = Level(
    "ride",
    RIDE_LAYER_MIN_ZOOM,
    4096,
    32,
    None,
    merged=True,
    predicate=ride_layer_predicate,
)
BUSY = Level("busy", RIDE_LAYER_MIN_ZOOM, 4096, 32, None, merged=True, predicate=busy_predicate)
FULL = Level("full", QUIET_STREETS_MIN_ZOOM, 4096, 64, None, merged=False)
LEVELS = (FULL, BUSY, TRAILS_NEAR, TRAILS)


def level_for(z: int, optional: frozenset[str] = frozenset()) -> Level:
    """The level a tile at `z` is drawn at, on a table with the `optional` columns:
    z12-13 is the ride layer where there is a `calm_run_m` to draw it from, and the
    busy roads (what it was before OWNER-DECISIONS 391) where there is not."""
    level = next(level for level in LEVELS if z >= level.min_zoom)
    if level is BUSY and CALM_RUN_COLUMN in optional:
        return RIDE_LAYER
    return level


def tile_bounds(z: int, x: int, y: int) -> tuple[float, float, float, float]:
    """(west, south, east, north) in degrees."""
    n = 2**z

    def lat(row: int) -> float:
        return math.degrees(math.atan(math.sinh(math.pi * (1 - 2 * row / n))))

    return x / n * 360 - 180, lat(y + 1), (x + 1) / n * 360 - 180, lat(y)


def outside_coverage(z: int, x: int, y: int) -> bool:
    west, south, east, north = tile_bounds(z, x, y)
    c_west, c_south, c_east, c_north = settings.COVERAGE_BBOX
    return east < c_west or west > c_east or north < c_south or south > c_north


def straddles_coverage(z: int, x: int, y: int, margin: float) -> bool:
    """Whether the tile, with `margin` of its width drawn past each edge,
    reaches past the coverage box - and so has to be clipped to it."""
    west, south, east, north = tile_bounds(z, x, y)
    dx, dy = (east - west) * margin, (north - south) * margin
    c_west, c_south, c_east, c_north = settings.COVERAGE_BBOX
    return west - dx < c_west or east + dx > c_east or south - dy < c_south or north + dy > c_north


# Each feature's properties, as {tile property: segment column}: the one place
# that says what a tile carries. A value is carried as the column holds it, so
# a new tier value reaches the tile unchanged; a new property is a new entry
# here (and, if the zoomed-out levels should keep it, a term in
# pipeline.schema's predicates). A null is left out of the feature rather than
# sent - an unknown surface is not "paved".
PROPERTIES = {"tier": "stress_tier", "trail": "is_trail_class", "unpaved": "is_unpaved"}

# Properties carried only from a live table that has the column: the bike
# facility (path, protected, lane, none), which the rebuild writes from
# `routemaker.facility`, and a table promoted before it has no such column. Where it is
# there, the zoomed-out levels draw its paths and trails. Where it is not, a
# stand-in is carried in its place (`FALLBACKS`) and the zoomed-out paths are
# the ones that stand-in calls a path. `separate_bikeway` (true, or left out)
# is what the map draws a road beside a separately mapped bike facility faint
# by (OWNER-DECISIONS 73, 78). `map_class` is not carried: only a road is in
# the tiles at all (80, 82, 88, 89).
OPTIONAL_PROPERTIES = {
    "facility": FACILITY_COLUMN,
    "car_free": CAR_FREE_COLUMN,
    "map_class": MAP_CLASS_COLUMN,
    "separate_bikeway": SEPARATE_BIKEWAY_COLUMN,
    # NO-BIKE-PATHS (OWNER-DECISIONS 290, 291): `mtb` marks a trail only a
    # mountain bike rides (kept open for Gravel and Mountain Goat, closed for
    # the rest) and `rough` a surface that sheds riders. The map draws an `mtb`
    # trail in its own not-for-routes look, a thin dotted grey line, and in no
    # routable layer (452a, superseding 452's hiding and 290(b)'s faint drawing;
    # frontend/src/stressStyle.js, `mtb-trail`); a future MTB mode would draw it
    # as routable. `rough` is not read: such a trail draws as any unpaved one,
    # with no path rail (290(a)).
    # Each is true or left out.
    "mtb": MTB_ONLY_COLUMN,
    "rough": ROUGH_COLUMN,
    # OWNER-DECISIONS 403: a trail beside a road, which the map draws as a paved path
    # where no surface is mapped (not 376 A's surface-unknown dashes). True or left out.
    "roadside": ROADSIDE_COLUMN,
    # The Mass Ride capacity (OWNER-DECISIONS 325-327, 387), riders a minute, from the
    # usable width (404-407).
    "rpm": MASS_WIDTH_COLUMN,
}

# The tile property `rpm` is rounded down to a multiple of this (OPTIONAL_EXPRESSIONS).
RPM_STEP = 10
# Riders a minute for each metre of usable width, from `routemaker.flow`: the column holds
# the width, and the tile computes the riders, so tuning the constants needs no rebuild.
# But neither tile tag carries this figure, so a tuned constant must bump BOTH
# FORMAT_VERSIONs (this module's and core.mass_tiles'), or the tile cache and the
# browsers' 304s keep the old `rpm` while the route chart, computed at request time,
# moves at once (REBUILD-BUNDLE correctness review, nit 3).
# tests/test_stress_tiles.py holds the figure to the format versions it was drawn at.
RPM_PER_METRE_SQL = repr(round(flow.level_riders_per_min(1.0), 6))

# How an optional property is drawn from its column, where it is not the
# column as it is. `car_free`: the ride times a road closed to motor traffic
# at set times is car-free in, comma-separated ("weekend"), and left out of a
# feature that has none - a road closed for good is a path already. The map's
# style reads it against the ride time it follows (frontend/src/stressStyle.js,
# `stressFilters`): in one of them the road draws as an off-road path, tier 1,
# and otherwise with its own stress (the owner, 2026-09-29: "Car-free roads
# should be regarded the same as an off-road path on a map."; OWNER-DECISIONS
# 67). One tile serves every ride time, so the pre-draw draws each tile once.
OPTIONAL_EXPRESSIONS = {
    "car_free": f"NULLIF(array_to_string(s.{CAR_FREE_COLUMN}, ','), '')",
    "separate_bikeway": f"NULLIF(s.{SEPARATE_BIKEWAY_COLUMN}, false)",
    "mtb": f"NULLIF(s.{MTB_ONLY_COLUMN}, false)",
    "rough": f"NULLIF(s.{ROUGH_COLUMN}, false)",
    "roadside": f"NULLIF(s.{ROADSIDE_COLUMN}, false)",
    # `rpm`: the Mass Ride capacity, riders a minute, rounded DOWN to a multiple of
    # RPM_STEP. The Mass Ride bands (60, 120, 200) are multiples of it, so a
    # feature never moves band; and the zoomed-out levels, which collect every
    # segment of one value into one feature, are not split into a feature per
    # distinct figure (one per integer would be about 400 values a class).
    "rpm": (
        f"(floor(round(s.{MASS_WIDTH_COLUMN}::numeric * {RPM_PER_METRE_SQL}) / {RPM_STEP}.0)"
        f" * {RPM_STEP})::int"
    ),
}

# What an optional property is drawn from on a table without its column: the
# facility is derived from the trail network (an off-road path, or nothing),
# so the trails carry the path's rails at every zoom before the column exists;
# and a road beside a separate bikeway is not known, so none is drawn faint
# for it.
FALLBACKS = {"facility": TRAIL_NETWORK_FACILITY}

# The three columns the long-trails rule reads (OWNER-DECISIONS 375, 377), which the
# rebuild writes from the OSM route relations and way names
# (`pipeline.trail_routes`). Not carried in a tile: they only choose which ways
# the z10-11 tiles hold. A table promoted before them has none of them, and its
# zoomed-out tiles keep every path and trail, as they did; the rule applies
# only where all three are there. A data rebuild adds them; nothing else does.
LONG_TRAIL_COLUMNS = (TRAIL_ROUTE_COLUMN, TRAIL_RUN_COLUMN, TRAIL_BRIDGE_COLUMN)

_MERGED = """
WITH bounds AS (SELECT ST_TileEnvelope(%(z)s, %(x)s, %(y)s) AS env),
features AS (
    SELECT {columns},
           ST_AsMVTGeom(
               ST_Simplify(ST_Collect(ST_Transform({geometry}, 3857)), %(unit)s),
               bounds.env, %(extent)s, %(buffer)s, true
           ) AS geom
    FROM {table} AS s, bounds
    WHERE s.geometry && ST_Transform(
              ST_TileEnvelope(%(z)s, %(x)s, %(y)s, margin => %(margin)s), 4326)
      {coverage}
      AND {where}
    GROUP BY {group_by}, bounds.env
)
SELECT '{table}'::regclass::oid,
       (SELECT ST_AsMVT(features.*, '{layer}', %(extent)s, 'geom') FROM features)
"""

_PER_SEGMENT = """
WITH bounds AS (SELECT ST_TileEnvelope(%(z)s, %(x)s, %(y)s) AS env),
features AS (
    SELECT {columns},
           ST_AsMVTGeom(ST_Transform({geometry}, 3857), bounds.env, %(extent)s, %(buffer)s, true)
               AS geom
    FROM {table} AS s, bounds
    WHERE s.geometry && ST_Transform(
              ST_TileEnvelope(%(z)s, %(x)s, %(y)s, margin => %(margin)s), 4326)
      {coverage}
      AND {where}
)
SELECT '{table}'::regclass::oid,
       (SELECT ST_AsMVT(features.*, '{layer}', %(extent)s, 'geom') FROM features)
"""


def _table() -> str:
    # The schema name comes from settings and is validated the way every DDL
    # naming it is; an identifier cannot be a query parameter.
    return f"{validate_schema_name(settings.SEGMENT_SCHEMA_LIVE)}.segment"


# The coverage box, as the clipped query reads it from its parameters.
_COVERAGE_BOX = "ST_MakeEnvelope(%(c_west)s, %(c_south)s, %(c_east)s, %(c_north)s, 4326)"


def tile_sql(level: Level, optional: frozenset[str] = frozenset(), clip: bool = False) -> str:
    """The level's query, carrying the optional columns in `optional` too, and
    with `clip`, drawing only what lies inside the coverage box."""
    template = _MERGED if level.merged else _PER_SEGMENT
    carried = {name: f"s.{column}" for name, column in PROPERTIES.items()}
    for name, column in OPTIONAL_PROPERTIES.items():
        if column in optional:
            carried[name] = OPTIONAL_EXPRESSIONS.get(name, f"s.{column}")
        elif name in FALLBACKS:
            carried[name] = FALLBACKS[name]
    has_facility = FACILITY_COLUMN in optional
    has_car_free = CAR_FREE_COLUMN in optional
    if level.predicate is not None:
        where = level.predicate(has_facility, has_car_free)
        if level.long_trails is not None and all(c in optional for c in LONG_TRAIL_COLUMNS):
            rule = long_trails_predicate(level.long_trails, has_car_free)
            where = f"({where}) AND {rule}"
        if has_car_free:
            # A road closed to cars at set times is in a zoomed-out tile that
            # would not otherwise hold it only for those times: it carries them
            # as `car_free_only`, and the map draws it only in one of them. A
            # way the level holds anyway keeps `car_free` as it is.
            kept = level.predicate(has_facility)
            expression = carried.pop("car_free")
            carried["car_free"] = f"CASE WHEN {kept} THEN {expression} END"
            carried["car_free_only"] = f"CASE WHEN NOT {kept} THEN {expression} END"
    else:
        where = level.where or "true"
    # Only a road is drawn: a public road a bicycle may not use is left to the
    # base map ("You can just leave the public roads where bikes aren't allowed
    # as unmarked, using the base map", OWNER-DECISIONS 89), and a way no
    # typical rider could use is not drawn (80, 82, 88). On a table without
    # the column the motorways are what the classifier recorded as motor-only.
    carried.pop("map_class", None)
    if MAP_CLASS_COLUMN in optional:
        # An alley is carried only at street level, marked `alley`, where the
        # map draws it only from close in, faint (OWNER-DECISIONS 100).
        if level.merged:
            where = f"({where}) AND s.{MAP_CLASS_COLUMN} = 'road'"
        else:
            where = f"({where}) AND s.{MAP_CLASS_COLUMN} IN ('road', 'alley')"
            carried["alley"] = f"CASE WHEN s.{MAP_CLASS_COLUMN} = 'alley' THEN true END"
    else:
        where = f"({where}) AND NOT {MOTOR_ONLY_RULE}"
    return template.format(
        table=_table(),
        where=where,
        geometry=f"ST_ClipByBox2D(s.geometry, {_COVERAGE_BOX})" if clip else "s.geometry",
        coverage=f"AND s.geometry && {_COVERAGE_BOX}" if clip else "",
        layer=LAYER,
        columns=", ".join(f"{expression} AS {name}" for name, expression in carried.items()),
        group_by=", ".join(carried.values()),
    )


class DrawTimedOut(Exception):
    """A tile draw ran past its statement timeout and was cancelled."""


def render(
    z: int,
    x: int,
    y: int,
    optional: frozenset[str] = frozenset(),
    timeout_ms: int | None = None,
) -> tuple[int, bytes]:
    """(the live table's oid, the tile's bytes) for a tile inside the zooms
    served, drawn under a `timeout_ms` statement timeout (DRAW_TIMEOUT_MS if
    none is given)."""
    if timeout_ms is None:
        timeout_ms = DRAW_TIMEOUT_MS
    level = level_for(z, optional)
    c_west, c_south, c_east, c_north = settings.COVERAGE_BBOX
    params = {
        "c_west": c_west,
        "c_south": c_south,
        "c_east": c_east,
        "c_north": c_north,
        "z": z,
        "x": x,
        "y": y,
        "extent": level.extent,
        "buffer": level.buffer,
        "margin": level.buffer / level.extent,
        # One tile unit, in metres of EPSG:3857: finer detail is not drawn.
        "unit": WORLD_M / 2**z / level.extent,
    }
    clip = straddles_coverage(z, x, y, level.buffer / level.extent)
    try:
        with transaction.atomic(), connection.cursor() as cursor:
            cursor.execute("SELECT set_config('statement_timeout', %s, true)", [str(timeout_ms)])
            cursor.execute(tile_sql(level, optional, clip), params)
            oid, tile = cursor.fetchone()
    except OperationalError as error:
        if getattr(error.__cause__, "sqlstate", None) == "57014":  # query_canceled
            raise DrawTimedOut(f"tile {z}/{x}/{y} ran past {timeout_ms} ms") from error
        raise
    return oid, bytes(tile or b"")


def live_table() -> tuple[int | None, frozenset[str]]:
    """The live table's oid, or None before any build, and which of the
    optional columns it has."""
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT t.oid, ARRAY(SELECT attname::text FROM pg_attribute WHERE attrelid = t.oid "
            "AND attname = ANY(%s) AND NOT attisdropped) "
            "FROM (SELECT to_regclass(%s)::oid AS oid) AS t",
            [[*OPTIONAL_PROPERTIES.values(), *LONG_TRAIL_COLUMNS, CALM_RUN_COLUMN], _table()],
        )
        oid, columns = cursor.fetchone()
    return oid, frozenset(columns or ())


ETAG_LETTERS = {
    FACILITY_COLUMN: "f",
    CAR_FREE_COLUMN: "c",
    MAP_CLASS_COLUMN: "m",
    SEPARATE_BIKEWAY_COLUMN: "s",
    TRAIL_BRIDGE_COLUMN: "b",
    TRAIL_ROUTE_COLUMN: "t",
    TRAIL_RUN_COLUMN: "l",
    CALM_RUN_COLUMN: "k",
    MTB_ONLY_COLUMN: "o",
    ROUGH_COLUMN: "r",
    ROADSIDE_COLUMN: "e",
    # `w` for width: `r` is the rough surface's (the bundle's two branches both took it).
    MASS_WIDTH_COLUMN: "w",
}


def etag_for(oid: int, optional: frozenset[str] = frozenset()) -> str:
    # Weak: the same table always draws the same features, but not always the
    # same bytes - ST_AsMVT's feature and value order follows the scan's row
    # order, and two draws of one z14 tile measured 124,520 and 124,532 bytes.
    # A strong tag promises byte-identical bodies (RFC 9110 8.8.1). The
    # optional columns are in it because a column added to the live table in
    # place (the facility, by hand) changes the tiles but not the table's oid.
    # Each column by a letter of its own, so the tag fits the cache's 64-character
    # key with all of them (a `+` and one letter each, twelve in all: `W/"stress-` and a
    # ten-digit oid, `+` and twelve letters, `-v7"`, 37 characters), in the order of the
    # column names.
    carried = "".join(ETAG_LETTERS[column] for column in sorted(optional))
    return f'W/"stress-{oid}{"+" + carried if carried else ""}-v{FORMAT_VERSION}"'


def _matches(request, etag: str) -> bool:
    header = request.META.get("HTTP_IF_NONE_MATCH", "")
    if not header:
        return False
    # If-None-Match uses the weak comparison (RFC 9110 13.1.2): W/ or not,
    # the same opaque tag matches.
    tags = [tag.removeprefix("W/") for tag in parse_etags(header)]
    return "*" in tags or etag.removeprefix("W/") in tags


def _tile_response(body: bytes, status: int = 200, etag: str | None = None) -> HttpResponse:
    response = HttpResponse(body, status=status, content_type=CONTENT_TYPE)
    patch_cache_control(response, public=True, max_age=MAX_AGE_S)
    if etag is not None:
        response["ETag"] = etag
    return response


@require_http_methods(["GET", "HEAD"])
@ratelimit.rate_limited(ratelimit.TILES)
def stress_tile(request, z: int, x: int, y: int) -> HttpResponse:
    if z > MAX_ADDRESSABLE_ZOOM or x >= 2**z or y >= 2**z:
        response = JsonResponse({"error": "not a tile address"}, status=400)
        response["Cache-Control"] = "no-store"
        return response
    if not MIN_ZOOM <= z <= MAX_ZOOM or outside_coverage(z, x, y):
        return _tile_response(b"")
    oid, optional = live_table()
    if oid is None:
        # No build has been promoted: nothing to draw, and the front end hides
        # the overlay on a 404 rather than showing a legend for nothing.
        response = JsonResponse({"error": "no stress data has been built yet"}, status=404)
        response["Cache-Control"] = "no-store"
        return response
    etag = etag_for(oid, optional)
    if _matches(request, etag):
        return _tile_response(b"", status=304, etag=etag)
    cached = tile_cache.get(etag, z, x, y)
    if cached is not None:
        return _tile_response(cached, etag=etag)
    held, refusal = ratelimit.acquire(request, ratelimit.TILES_IN_FLIGHT)
    if refusal is not None:
        refusal["Cache-Control"] = "no-store"
        return refusal
    try:
        try:
            drawn_oid, body = render(z, x, y, optional)
        except DrawTimedOut:
            response = JsonResponse(
                {"error": "This part of the stress map is taking too long; try again shortly."},
                status=503,
            )
            response["Retry-After"] = str(RETRY_AFTER_S)
            response["Cache-Control"] = "no-store"
            return response
    finally:
        ratelimit.release(held)
    if drawn_oid == oid:
        # Not when a promotion landed between the lookup and the draw: this
        # body belongs to the new table, and its own requests will cache it.
        # The Mass Ride tiles share the cache (core.mass_tiles): an eviction keeps theirs.
        from . import mass_tiles

        tile_cache.put(etag, z, x, y, body, also_keep=(mass_tiles.etag_for(oid, optional),))
    return _tile_response(body, etag=etag_for(drawn_oid, optional))
