#!/usr/bin/env python3
"""Extract the OSM keys the pinned Valhalla transform touches.

The quality bar requires the supported-key list to be read from the pinned
Valhalla source and checked into the repository, rather than believed. Valhalla's
tile schema is fixed and a key it does not read is silently dropped, so a remap
that writes one produces no error and no effect - the failure mode this list
exists to make impossible.

Run: python scripts/extract_valhalla_keys.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
VENDOR = REPO / "lua" / "vendor" / "graph_upstream.lua"
DESTINATION = REPO / "lua" / "vendor" / "supported_keys.txt"


def extract(source: str) -> list[str]:
    return sorted(set(re.findall(r'kv\["([^"]+)"\]', source)))


def main() -> int:
    version = (REPO / "lua" / "vendor" / "VERSION").read_text().strip()
    keys = extract(VENDOR.read_text())
    DESTINATION.write_text(
        f"# Keys Valhalla {version}'s lua/graph.lua reads or writes on the tag table.\n"
        f"# Generated by scripts/extract_valhalla_keys.py. Do not edit.\n"
        + "".join(f"{key}\n" for key in keys)
    )
    print(f"wrote {len(keys)} keys to {DESTINATION.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
